### ISSUE TITLE
how to configure print width to 120 characters? Thank You

### ISSUE THREAD

**Issue by asharimidana** [ruby-syntax-tree/prettier_print#9]
Example:
Following are the results of the auto format
```ruby
render json: {
               error: @user.errors.full_messages
             },
             status: :unprocessable_entity

```

I want the formatting results to work if the code we write exceeds 100 or 120 characters
like the following code:
```ruby
render json: { error: @user.errors.full_messages  }, status: :unprocessable_entity

```

**Comment by kddnewton** [comment]
Are you trying to use Syntax Tree or the prettier print library?
